#!/usr/bin/env bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR/.." || exit

./mvnw clean package
rm -rf ./target/keycloak
mkdir -p ./target/keycloak/providers
cp ./target/keycloak-2fa-email-authenticator-*.jar ./target/keycloak/providers
cp ./target/dependency/*.jar ./target/keycloak/providers
# cp -r ./templates/* ./target/keycloak/themes/base/login/
tar -czf ./target/keycloak-2fa-email-authenticator.tar.gz -C ./target/keycloak .

